#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

touch channelWithObstacle.foam

runApplication blockMesh

runApplication snappyHexMesh

#runApplication $(getApplication)

#foamLogs $(getApplication)

#------------------------------------------------------------------------------
